
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author JAVBit
 */
public class Publisher extends javax.swing.JFrame {

    /**
     * Creates new form Publisher
     */
    public Publisher() {
        initComponents();
        connect();
        loadPublisher();
        updateBtn.setEnabled(false);
        deleteBtn.setEnabled(false);
    }
    Connection con;
    PreparedStatement ps;
    ResultSet rs;

    //DB-Connection
    public void connect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/db_lms", "root", "");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Publisher.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Publisher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    //Load Catogory into Table
    public void loadPublisher() {

        try {
            ps = con.prepareStatement("select * from tbl_publisher");
            rs = ps.executeQuery();

            //GETTING THE TABLE MODEL OF catTable
            DefaultTableModel d1 = (DefaultTableModel) pubTable.getModel();
            d1.setRowCount(0);

            while (rs.next()) {
                Vector v2 = new Vector();
                v2.add(rs.getString("pub_id"));
                v2.add(rs.getString("name"));
                v2.add(rs.getString("phone"));
                v2.add(rs.getString("address"));
                d1.addRow(v2);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Publisher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        phoneField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        addressField = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        pubTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Publisher - Library Management System");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(90, 70, 127));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(57, 39, 89));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(129, 139, 235));
        jLabel1.setText("Publisher");

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(232, 240, 255));
        jLabel2.setText("Name");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(232, 240, 255));
        jLabel3.setText("Phone No.");

        addBtn.setForeground(new java.awt.Color(102, 102, 255));
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setForeground(new java.awt.Color(0, 160, 0));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setForeground(new java.awt.Color(255, 51, 51));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(232, 240, 255));
        jLabel4.setText("Address");

        jScrollPane2.setMaximumSize(new java.awt.Dimension(30, 30));

        addressField.setColumns(20);
        addressField.setRows(5);
        jScrollPane2.setViewportView(addressField);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(phoneField)
                            .addComponent(nameField)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(updateBtn))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 410));

        pubTable.setBackground(new java.awt.Color(204, 204, 255));
        pubTable.setForeground(new java.awt.Color(51, 0, 102));
        pubTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Publisher Name", "Phone No.", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pubTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pubTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(pubTable);
        if (pubTable.getColumnModel().getColumnCount() > 0) {
            pubTable.getColumnModel().getColumn(0).setMinWidth(70);
            pubTable.getColumnModel().getColumn(0).setPreferredWidth(70);
            pubTable.getColumnModel().getColumn(0).setMaxWidth(70);
            pubTable.getColumnModel().getColumn(1).setMinWidth(140);
            pubTable.getColumnModel().getColumn(1).setPreferredWidth(140);
            pubTable.getColumnModel().getColumn(1).setMaxWidth(140);
            pubTable.getColumnModel().getColumn(2).setMinWidth(110);
            pubTable.getColumnModel().getColumn(2).setPreferredWidth(110);
            pubTable.getColumnModel().getColumn(2).setMaxWidth(110);
            pubTable.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 560, 410));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // assigning values to variables
        String name = nameField.getText();
        String phone = phoneField.getText();
        String address = addressField.getText();

        if (!name.equals("")) {

                try {
                    //PREPARING QUERY
                    ps = con.prepareStatement("insert into tbl_publisher(name, phone, address) values (?, ?, ?)");
                    ps.setString(1, name);
                    ps.setString(2, phone);
                    ps.setString(3, address);
                    int res = ps.executeUpdate();

                    if (res == 1) {
                        loadPublisher();
                        JOptionPane.showMessageDialog(this, "Publisher Added Successfully!");
                        nameField.setText("");
                        phoneField.setText("");
                        addressField.setText("");
                        nameField.requestFocus();
                    } else {
                        JOptionPane.showMessageDialog(this, "Error While Adding Publisher!", "Error", JOptionPane.ERROR_MESSAGE);
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(Publisher.class.getName()).log(Level.SEVERE, null, ex);
                }
        } else {
            JOptionPane.showMessageDialog(jPanel1, "Name Field is Empty!", "Error", JOptionPane.WARNING_MESSAGE);
            nameField.requestFocus();
        }

    }//GEN-LAST:event_addBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel d1 = (DefaultTableModel) pubTable.getModel();
        int sIndex = pubTable.getSelectedRow();
        String name = d1.getValueAt(sIndex, 1).toString();
        int id = Integer.parseInt(d1.getValueAt(sIndex, 0).toString());

        int confirm = JOptionPane.showConfirmDialog(jPanel1, "Are you sure want to Delete " + name + "?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {

            try {
                //PREPARING QUERY
                ps = con.prepareStatement("delete from tbl_publisher where pub_id = ?");
                ps.setInt(1, id);
                int res = ps.executeUpdate();

                if (res == 1) {

                    loadPublisher();
                    JOptionPane.showMessageDialog(this, "Publisher Deleted Successfully!");
                    nameField.setText("");
                    phoneField.setText("");
                    addBtn.setEnabled(true);
                    deleteBtn.setEnabled(false);
                    addBtn.setForeground(new Color(102, 102, 255));
                    nameField.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(this, "Error While Deleting Publisher!", "Error", JOptionPane.ERROR_MESSAGE);
                }

            } catch (SQLException ex) {
                Logger.getLogger(Publisher.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_deleteBtnActionPerformed

    private void pubTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pubTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel d1 = (DefaultTableModel) pubTable.getModel();

        //ASSIGNING THE SELECTED ROW
        int sIndex = pubTable.getSelectedRow();

        //SETTING THE FIELDS
        nameField.setText(d1.getValueAt(sIndex, 1).toString());
        phoneField.setText(d1.getValueAt(sIndex, 2).toString());
        addressField.setText(d1.getValueAt(sIndex, 3).toString());

        //ENABLING UPDATE BUTTON
        updateBtn.setEnabled(true);
        deleteBtn.setEnabled(true);
        
        //DISABLING THE ADD BUTTON
        addBtn.setEnabled(false);
        addBtn.setForeground(new Color(204, 204, 255));

    }//GEN-LAST:event_pubTableMouseClicked

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel d1 = (DefaultTableModel) pubTable.getModel();

        //ASSIGNING THE SELECTED ROW
        int sIndex = pubTable.getSelectedRow();

        //ASSIGNING THE ID OF SELECTED Publisher
        int id = Integer.parseInt(d1.getValueAt(sIndex, 0).toString());

        // ASSIGNING VALUES TO THE VARIABLES
        String name = nameField.getText();
        String phone = phoneField.getText();
        String address = addressField.getText();
        
        if (!name.equals("")) {

                try {
                    //PREPARING QUERY
                    ps = con.prepareStatement("update tbl_publisher set name =  ?, phone = ?, address = ? where pub_id = ?");
                    ps.setString(1, name);
                    ps.setString(2, phone);
                    ps.setString(3, address);
                    ps.setInt(4, id);
                    int res = ps.executeUpdate();

                    if (res == 1) {
                        loadPublisher();
                        JOptionPane.showMessageDialog(this, "Publisher Updated Successfully!");
                        nameField.setText("");
                        phoneField.setText("");
                        addressField.setText("");
                        updateBtn.setEnabled(false);
                        addBtn.setEnabled(true);
                        addBtn.setForeground(new Color(102, 102, 255));
                        nameField.requestFocus();
                    } else {
                        JOptionPane.showMessageDialog(this, "Error While Updating Publisher!");
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(Publisher.class.getName()).log(Level.SEVERE, null, ex);
                }
            }  else {
            JOptionPane.showMessageDialog(jPanel1, "First Name Field is Empty!", "Error", JOptionPane.WARNING_MESSAGE);
            nameField.requestFocus();
        }

    }//GEN-LAST:event_updateBtnActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Publisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Publisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Publisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Publisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Publisher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextArea addressField;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JTable pubTable;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
